version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
        - shadow
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
